const placesData = [
  // ====== Family ======
  { id: 'disney', name: '香港迪士尼樂園', emoji: '🏰', category: 'family', lat: 22.3140, lng: 114.0410, section: 'family', link: 'explore.html#family' },
  { id: 'ocean-park', name: '香港海洋公園', emoji: '🐬', category: 'family', lat: 22.2460, lng: 114.1740, section: 'family', link: 'explore.html#family' },
  { id: 'science-museum', name: '香港科學館 · 太空館', emoji: '🔬', category: 'family', lat: 22.3010, lng: 114.1730, section: 'family', link: 'explore.html#family' },
  { id: 'star-ferry', name: '天星小輪 & 維港', emoji: '🚢', category: 'family', lat: 22.2950, lng: 114.1690, section: 'family', link: 'explore.html#family' },
  { id: 'west-kowloon-family', name: '西九文化區大草坪', emoji: '🧺', category: 'family', lat: 22.2920, lng: 114.1570, section: 'family', link: 'explore.html#family' },
  { id: 'cycling-park', name: '香港單車館公園', emoji: '🚴', category: 'family', lat: 22.3200, lng: 114.2650, section: 'family', link: 'explore.html#family' },
  { id: 'gold-coast', name: '黃金海岸', emoji: '🏖️', category: 'family', lat: 22.3700, lng: 113.9900, section: 'family', link: 'explore.html#family' },
  { id: 'lychee-wal', name: '荔枝窩 · 300年客家圍村', emoji: '🌳', category: 'family', lat: 22.5130, lng: 114.2730, section: 'family', link: 'explore.html#family' },
  { id: 'lau-fau-shan', name: '流浮山 · 蠔田日落', emoji: '🦪', category: 'family', lat: 22.4650, lng: 113.9780, section: 'family', link: 'explore.html#family' },
  { id: 'kung-so', name: '公和荳品廠 · 百年豆品', emoji: '🥟', category: 'family', lat: 22.3300, lng: 114.1620, section: 'family', link: 'explore.html#family' },
  { id: 'kowloon-city-food', name: '九龍城 · 泰國菜集中地', emoji: '🍜', category: 'family', lat: 22.3280, lng: 114.1870, section: 'family', link: 'explore.html#family' },
  { id: 'kadoorie', name: '嘉道理農場', emoji: '🌳', category: 'family', lat: 22.4400, lng: 114.1170, section: 'family', link: 'explore.html#family' },
  { id: 'kat-o', name: '吉澳', emoji: '🏝️', category: 'family', lat: 22.5470, lng: 114.2840, section: 'family', link: 'explore.html#family' },

  // ====== Youth ======
  { id: 'central-murals', name: '中環壁畫街 & PMQ', emoji: '🎨', category: 'youth', lat: 22.2830, lng: 114.1520, section: 'youth', link: 'explore.html#youth' },
  { id: 'mongkok-night', name: '旺角夜市 & 深水埗', emoji: '🌃', category: 'youth', lat: 22.3200, lng: 114.1690, section: 'youth', link: 'explore.html#youth' },
  { id: 'lamma', name: '南丫島徒步', emoji: '🏝️', category: 'youth', lat: 22.1980, lng: 114.1140, section: 'youth', link: 'explore.html#youth' },
  { id: 'victoria-peak', name: '太平山夜景', emoji: '🌄', category: 'youth', lat: 22.2760, lng: 114.1450, section: 'youth', link: 'explore.html#youth' },
  { id: 'coffee-route', name: '咖啡館打卡路線', emoji: '☕', category: 'youth', lat: 22.2810, lng: 114.1280, section: 'youth', link: 'explore.html#youth' },
  { id: 'sai-wan-pier-youth', name: '西環泳棚', emoji: '🌅', category: 'youth', lat: 22.2770, lng: 114.1210, section: 'youth', link: 'explore.html#youth' },
  { id: 'monster-building-youth', name: '怪獸大厦', emoji: '🏗️', category: 'youth', lat: 22.2870, lng: 114.2100, section: 'youth', link: 'explore.html#youth' },
  { id: 'peng-chau-youth', name: '坪洲 · 寧靜離島', emoji: '🏝️', category: 'youth', lat: 22.2870, lng: 114.0390, section: 'youth', link: 'explore.html#youth' },
  { id: 'bishop-hill', name: '主教山配水庫', emoji: '🏛️', category: 'youth', lat: 22.3340, lng: 114.1650, section: 'youth', link: 'explore.html#youth' },
  { id: 'tai-hang', name: '大坑 · 銅鑼灣旁邊兩個世界', emoji: '🏘️', category: 'youth', lat: 22.2780, lng: 114.1920, section: 'youth', link: 'explore.html#youth' },
  { id: 'sing-heung', name: '勝香園 · 中環鐵皮檔茄牛通', emoji: '🍜', category: 'youth', lat: 22.2840, lng: 114.1530, section: 'youth', link: 'explore.html#youth' },
  { id: 'd2-place', name: 'D2 Place · 週末文創市集', emoji: '🎨', category: 'youth', lat: 22.3370, lng: 114.1450, section: 'youth', link: 'explore.html#youth' },
  { id: 'sai-kung-bridge', name: '西貢 + 橋咀洲', emoji: '🏝️', category: 'youth', lat: 22.3820, lng: 114.2730, section: 'youth', link: 'explore.html#youth' },
  { id: 'tung-lung', name: '東龍島', emoji: '🏝️', category: 'youth', lat: 22.2500, lng: 114.2950, section: 'youth', link: 'explore.html#youth' },
  { id: 'nam-sang-wai', name: '南生圍', emoji: '🌿', category: 'youth', lat: 22.4700, lng: 114.0400, section: 'youth', link: 'explore.html#youth' },
  { id: 'green-egg', name: '綠蛋島', emoji: '🥚', category: 'youth', lat: 22.3300, lng: 114.3200, section: 'youth', link: 'explore.html#youth' },
  { id: 'san-po-kong', name: '新蒲崗美食圈', emoji: '🍜', category: 'youth', lat: 22.3380, lng: 114.1980, section: 'youth', link: 'explore.html#youth' },
  { id: 'shek-mun', name: '石門美食圈', emoji: '🍜', category: 'youth', lat: 22.3880, lng: 114.2080, section: 'youth', link: 'explore.html#youth' },
  { id: 'ngau-shi-wu', name: '牛屎湖', emoji: '🌊', category: 'youth', lat: 22.5050, lng: 114.2780, section: 'youth', link: 'explore.html#youth' },
  { id: 'm-plus', name: 'M+博物館', emoji: '🏛️', category: 'youth', lat: 22.2910, lng: 114.1550, section: 'youth', link: 'explore.html#youth' },
  { id: 'cheung-chau-youth', name: '長洲島', emoji: '🏝️', category: 'youth', lat: 22.2100, lng: 114.0280, section: 'youth', link: 'explore.html#youth' },
  { id: 'pmq-youth', name: 'PMQ元創方 x HKwalls', emoji: '🎨', category: 'youth', lat: 22.2830, lng: 114.1520, section: 'youth', link: 'explore.html#youth' },
  { id: 'lan-kwai-fong', name: '蘭桂坊', emoji: '🎉', category: 'youth', lat: 22.2800, lng: 114.1550, section: 'youth', link: 'explore.html#youth' },

  // ====== Adult ======
  { id: 'mid-levels', name: '半山扶梯漫步', emoji: '🛗', category: 'adult', lat: 22.2820, lng: 114.1540, section: 'adult', link: 'explore.html#adult' },
  { id: 'pottinger', name: '石板街 & 大館', emoji: '🗿', category: 'adult', lat: 22.2810, lng: 114.1560, section: 'adult', link: 'explore.html#adult' },
  { id: 'sai-kung-seafood', name: '西貢海鮮', emoji: '🦐', category: 'adult', lat: 22.3820, lng: 114.2730, section: 'adult', link: 'explore.html#adult' },
  { id: 'tai-o', name: '大澳漁村', emoji: '🏘️', category: 'adult', lat: 22.2540, lng: 113.8640, section: 'adult', link: 'explore.html#adult' },
  { id: 'harbour-cruise', name: '維港夜遊船', emoji: '🚢', category: 'adult', lat: 22.2930, lng: 114.1710, section: 'adult', link: 'explore.html#adult' },
  { id: 'pmq-adult', name: 'PMQ元創方', emoji: '🎨', category: 'adult', lat: 22.2830, lng: 114.1520, section: 'adult', link: 'explore.html#adult' },
  { id: 'western-market', name: '西環碼頭', emoji: '🌉', category: 'adult', lat: 22.2840, lng: 114.1240, section: 'adult', link: 'explore.html#adult' },
  { id: 'camel-paint', name: '駱駝漆大廈', emoji: '🏭', category: 'adult', lat: 22.3120, lng: 114.2270, section: 'adult', link: 'explore.html#adult' },
  { id: 'sunny-bay', name: '欣澳長索島', emoji: '🏝️', category: 'adult', lat: 22.3250, lng: 114.0000, section: 'adult', link: 'explore.html#adult' },
  { id: 'haiphong-road', name: '海防道熟食市場', emoji: '🍽️', category: 'adult', lat: 22.2970, lng: 114.1710, section: 'adult', link: 'explore.html#adult' },
  { id: 'so-ke', name: '蘇記茶檔', emoji: '🍳', category: 'adult', lat: 22.3310, lng: 114.1630, section: 'adult', link: 'explore.html#adult' },
  { id: 'po-toi', name: '蒲台島', emoji: '🏝️', category: 'adult', lat: 22.1750, lng: 114.2500, section: 'adult', link: 'explore.html#adult' },
  { id: 'tung-ping-chau', name: '東平洲', emoji: '🪨', category: 'adult', lat: 22.5450, lng: 114.3270, section: 'adult', link: 'explore.html#adult' },
  { id: 'ozone', name: 'Ozone酒吧', emoji: '🍸', category: 'adult', lat: 22.3030, lng: 114.1610, section: 'adult', link: 'explore.html#adult' },
  { id: 'red-sugar', name: 'Red Sugar 紅糖', emoji: '🍷', category: 'adult', lat: 22.3020, lng: 114.1900, section: 'adult', link: 'explore.html#adult' },
  { id: 'peninsula', name: '半島酒店大堂茶座', emoji: '🏨', category: 'adult', lat: 22.2960, lng: 114.1710, section: 'adult', link: 'explore.html#adult' },

  // ====== Senior ======
  { id: 'old-tea-house', name: '老茶樓早茶攻略', emoji: '🍵', category: 'senior', lat: 22.2810, lng: 114.1580, section: 'senior', link: 'explore.html#senior' },
  { id: 'ngong-ping', name: '昂坪360 & 寶蓮禪寺', emoji: '🚡', category: 'senior', lat: 22.2540, lng: 113.9020, section: 'senior', link: 'explore.html#senior' },
  { id: 'nan-lian', name: '南蓮園池 & 志蓮淨苑', emoji: '🌿', category: 'senior', lat: 22.3400, lng: 114.2020, section: 'senior', link: 'explore.html#senior' },
  { id: 'flower-market', name: '花墟 & 雀鳥花園', emoji: '🌸', category: 'senior', lat: 22.3260, lng: 114.1710, section: 'senior', link: 'explore.html#senior' },
  { id: 'kowloon-park', name: '九龍公園晨運', emoji: '🏸', category: 'senior', lat: 22.3010, lng: 114.1690, section: 'senior', link: 'explore.html#senior' },
  { id: 'hong-kong-park', name: '香港公園', emoji: '🌳', category: 'senior', lat: 22.2770, lng: 114.1620, section: 'senior', link: 'explore.html#senior' },
  { id: 'kowloon-walled', name: '九龍寨城公園', emoji: '🏯', category: 'senior', lat: 22.3320, lng: 114.1890, section: 'senior', link: 'explore.html#senior' },
  { id: 'hong-kong-park-senior', name: '香港公園 · 銀髮慢活', emoji: '🌿', category: 'senior', lat: 22.2770, lng: 114.1620, section: 'senior', link: 'explore.html#senior' },
  { id: 'tung-chung-xinhua', name: '東涌新華酒家', emoji: '🍚', category: 'senior', lat: 22.2890, lng: 113.9460, section: 'senior', link: 'explore.html#senior' },
  { id: 'lei-yue-mun', name: '鯉魚門三家村', emoji: '🐟', category: 'senior', lat: 22.2930, lng: 114.2390, section: 'senior', link: 'explore.html#senior' },

  // ====== Quiet ======
  { id: 'west-kowloon-waterfront', name: '西九海濱 · 睇日落', emoji: '🌅', category: 'quiet', lat: 22.2920, lng: 114.1570, section: 'quiet', link: 'explore.html#quiet' },
  { id: 'central-pier', name: '中環碼頭 · 睇船', emoji: '⛵', category: 'quiet', lat: 22.2870, lng: 114.1580, section: 'quiet', link: 'explore.html#quiet' },
  { id: 'shek-o', name: '石澳海灘 · 黃昏', emoji: '🏖️', category: 'quiet', lat: 22.2300, lng: 114.2450, section: 'quiet', link: 'explore.html#quiet' },
  { id: 'tai-mo-shan', name: '大帽山 · 睇雲', emoji: '⛰️', category: 'quiet', lat: 22.4100, lng: 114.1200, section: 'quiet', link: 'explore.html#quiet' },
  { id: 'old-tea-house-quiet', name: '老茶樓 · 一個人', emoji: '🍵', category: 'quiet', lat: 22.2810, lng: 114.1580, section: 'quiet', link: 'explore.html#quiet' },
  { id: 'eslite', name: '誠品書店 · 窗邊位', emoji: '📖', category: 'quiet', lat: 22.2800, lng: 114.1860, section: 'quiet', link: 'explore.html#quiet' },
  { id: 'peng-chau-quiet', name: '坪洲 · 全日放空', emoji: '🏝️', category: 'quiet', lat: 22.2870, lng: 114.0390, section: 'quiet', link: 'explore.html#quiet' },
  { id: 'hong-kong-park-birds', name: '香港公園 · 觀鳥園', emoji: '🦜', category: 'quiet', lat: 22.2770, lng: 114.1620, section: 'quiet', link: 'explore.html#quiet' },
  { id: 'pokfulam', name: '薄扶林水塘', emoji: '🌲', category: 'quiet', lat: 22.2710, lng: 114.1350, section: 'quiet', link: 'explore.html#quiet' },
  { id: 'tap-mun', name: '塔門 · 香港無添', emoji: '🐂', category: 'quiet', lat: 22.4760, lng: 114.3630, section: 'quiet', link: 'explore.html#quiet' },
  { id: 'kennedy-town', name: '堅尼地城海旁 · 西環日落', emoji: '🌅', category: 'quiet', lat: 22.2820, lng: 114.1260, section: 'quiet', link: 'explore.html#quiet' },
  { id: 'lau-sap-heung', name: '流水響水塘', emoji: '🌲', category: 'quiet', lat: 22.4990, lng: 114.1550, section: 'quiet', link: 'explore.html#quiet' },
  { id: 'tung-chung-east', name: '東涌東海濱長廊', emoji: '🌅', category: 'quiet', lat: 22.2890, lng: 113.9450, section: 'quiet', link: 'explore.html#quiet' },
  { id: 'nan-lian-quiet', name: '南蓮園池 & 志蓮淨苑', emoji: '🏯', category: 'quiet', lat: 22.3400, lng: 114.2020, section: 'quiet', link: 'explore.html#quiet' },

  // ====== Photo ======
  { id: 'kennedy-basketball', name: '堅尼地城籃球場', emoji: '🏀', category: 'photo', lat: 22.2810, lng: 114.1230, section: 'photo', link: 'explore.html#photo' },
  { id: 'sai-wan-pier-photo', name: '西環泳棚 · 海邊棧橋', emoji: '🌉', category: 'photo', lat: 22.2770, lng: 114.1210, section: 'photo', link: 'explore.html#photo' },
  { id: 'monster-building-photo', name: '怪獸大厦 · 極繁美學', emoji: '🏗️', category: 'photo', lat: 22.2870, lng: 114.2100, section: 'photo', link: 'explore.html#photo' },
  { id: 'lok-wah', name: '樂華南邨 · 時光隧道', emoji: '🌀', category: 'photo', lat: 22.3200, lng: 114.2200, section: 'photo', link: 'explore.html#photo' },
  { id: 'choi-hung', name: '彩虹邨 · 彩色球場', emoji: '🌈', category: 'photo', lat: 22.3360, lng: 114.2080, section: 'photo', link: 'explore.html#photo' },
  { id: 'hung-heung-lo', name: '紅香爐峰', emoji: '🏔️', category: 'photo', lat: 22.2880, lng: 114.2000, section: 'photo', link: 'explore.html#photo' },
  { id: 'finger-hill', name: '坪洲手指山 · 360度全景', emoji: '⛰️', category: 'photo', lat: 22.2830, lng: 114.0400, section: 'photo', link: 'explore.html#photo' },
  { id: 'yim-tin-tsai', name: '鹽田梓', emoji: '🧂', category: 'photo', lat: 22.3700, lng: 114.3100, section: 'photo', link: 'explore.html#photo' },
  { id: 'aberdeen', name: '香港仔避風塘', emoji: '⛵', category: 'photo', lat: 22.2480, lng: 114.1530, section: 'photo', link: 'explore.html#photo' },

  // ====== Food (from food.html) ======
  { id: 'hung-cha', name: '紅茶冰室', emoji: '🥇', category: 'food', lat: 22.2960, lng: 114.1710, section: 'food', link: 'food.html#cha-chaan-teng' },
  { id: 'lan-fong-yuen', name: '蘭芳園 · 絲襪奶茶始祖', emoji: '🫖', category: 'food', lat: 22.2810, lng: 114.1550, section: 'food', link: 'food.html#cha-chaan-teng' },
  { id: 'waso', name: '華嫂冰室', emoji: '🍅', category: 'food', lat: 22.2960, lng: 114.1710, section: 'food', link: 'food.html#cha-chaan-teng' },
  { id: 'wong-ke', name: '旺記冰室 · 滑蛋專家', emoji: '🥚', category: 'food', lat: 22.3200, lng: 114.1690, section: 'food', link: 'food.html#cha-chaan-teng' },
  { id: 'bing-kei', name: '炳記茶檔 · 鐵皮奶茶王', emoji: '🏆', category: 'food', lat: 22.2780, lng: 114.1920, section: 'food', link: 'food.html#cha-chaan-teng' },
  { id: '18-seats', name: '十八座狗仔粉', emoji: '🥇', category: 'food', lat: 22.3050, lng: 114.1690, section: 'food', link: 'food.html#street-food' },
  { id: 'mommy-egg', name: '媽咪雞蛋仔', emoji: '🧇', category: 'food', lat: 22.2960, lng: 114.1710, section: 'food', link: 'food.html#street-food' },
  { id: 'hop-yick', name: '合益泰小食 · 深水埗腸粉王', emoji: '🥟', category: 'food', lat: 22.3300, lng: 114.1600, section: 'food', link: 'food.html#street-food' },
  { id: 'tung-tat', name: '通達食店 · 油麻地掃街', emoji: '🥣', category: 'food', lat: 22.3120, lng: 114.1700, section: 'food', link: 'food.html#street-food' },
  { id: 'kams', name: '甘牌燒鵝 · 米芝蓮一星', emoji: '🦆', category: 'food', lat: 22.2780, lng: 114.1730, section: 'food', link: 'food.html#roast' },
  { id: 'yat-lok', name: '一樂燒鵝 · 中環米芝蓮', emoji: '🦆', category: 'food', lat: 22.2810, lng: 114.1570, section: 'food', link: 'food.html#roast' },
  { id: 'joy-hing', name: '再興燒臘 · CNN叉燒王者', emoji: '🥩', category: 'food', lat: 22.2780, lng: 114.1730, section: 'food', link: 'food.html#roast' },
  { id: 'tim-ho-wan', name: '添好運 · 全球最平米芝蓮', emoji: '🥟', category: 'food', lat: 22.3300, lng: 114.1610, section: 'food', link: 'food.html#dimsum' },
  { id: 'lin-heung', name: '蓮香樓 · 百年推車點心', emoji: '🏛️', category: 'food', lat: 22.2830, lng: 114.1520, section: 'food', link: 'food.html#dimsum' },
  { id: 'sun-hing', name: '新興食家 · 陳奕迅都愛嘅夜茶', emoji: '🌙', category: 'food', lat: 22.2820, lng: 114.1200, section: 'food', link: 'food.html#dimsum' },
  { id: 'ka-ka', name: '佳佳甜品 · 米芝蓮九年', emoji: '🥇', category: 'food', lat: 22.3040, lng: 114.1680, section: 'food', link: 'food.html#dessert' },
  { id: 'bakehouse', name: 'Bakehouse · 全港最好食蛋撻', emoji: '🥐', category: 'food', lat: 22.2800, lng: 114.1740, section: 'food', link: 'food.html#dessert' },
  { id: 'yuk-yip', name: '玉葉甜品 · 百年鐵皮檔糖水', emoji: '🌿', category: 'food', lat: 22.2820, lng: 114.1540, section: 'food', link: 'food.html#dessert' },
  { id: 'chan-kan-kei', name: '陳勤記 · 米芝蓮潮州菜', emoji: '🥇', category: 'food', lat: 22.2830, lng: 114.1520, section: 'food', link: 'food.html#chiu-chow' },
  { id: 'man-kei', name: '文記車仔麵 · 深水埗之王', emoji: '🍜', category: 'food', lat: 22.3300, lng: 114.1600, section: 'food', link: 'food.html#cart-noodles' },
  { id: 'kwan-kei', name: '坤記煲仔小菜 · 米芝蓮煲仔飯', emoji: '🍚', category: 'food', lat: 22.2850, lng: 114.1350, section: 'food', link: 'food.html#claypot' },
  { id: 'hei-kei', name: '喜記避風塘炒辣蟹', emoji: '🦀', category: 'food', lat: 22.2800, lng: 114.1860, section: 'food', link: 'food.html#seafood' },
  { id: 'kau-keung', name: '九記牛腩 · 中環排隊傳奇', emoji: '🥇', category: 'food', lat: 22.2830, lng: 114.1540, section: 'food', link: 'food.html#hidden' },
  { id: 'little-bao', name: 'Little Bao · 亞洲最佳女廚', emoji: '🍔', category: 'food', lat: 22.2840, lng: 114.1530, section: 'food', link: 'food.html#hidden' },

  // ====== Explore page additions ======
  { id: 'zoo-botanic', name: '香港動植物公園', emoji: '🌿', category: 'family', lat: 22.2770, lng: 114.1570, section: 'family', link: 'explore.html#family' },
  { id: 'yuen-long-bird', name: '元朗公園百鳥塔', emoji: '🐦', category: 'family', lat: 22.4440, lng: 114.0240, section: 'family', link: 'explore.html#family' },
  { id: 'haiphong-market', name: '海防道臨時熟食市場', emoji: '🍜', category: 'adult', lat: 22.2990, lng: 114.1710, section: 'adult', link: 'explore.html#adult' },
  { id: 'statue-square', name: '遮打花園皇后像廣場', emoji: '🏛️', category: 'senior', lat: 22.2810, lng: 114.1600, section: 'senior', link: 'explore.html#senior' },
  { id: 'mid-levels-esc', name: '中環半山扶手電梯', emoji: '🛗', category: 'photo', lat: 22.2820, lng: 114.1550, section: 'photo', link: 'explore.html#photo' },
  { id: 'sai-wan-cargo', name: '西環貨物裝卸區', emoji: '📦', category: 'photo', lat: 22.2830, lng: 114.1270, section: 'photo', link: 'explore.html#photo' },
  { id: 'monster-building', name: '鰂魚涌海山樓', emoji: '🏗️', category: 'photo', lat: 22.2870, lng: 114.2100, section: 'photo', link: 'explore.html#photo' },
  { id: 'hk-island-route', name: '港島文化一日遊', emoji: '🚃', category: 'routes', lat: 22.2800, lng: 114.1600, section: 'routes', link: 'explore.html#routes' },
  { id: 'kowloon-food-walk', name: '九龍美食散步', emoji: '🥟', category: 'routes', lat: 22.3200, lng: 114.1690, section: 'routes', link: 'explore.html#routes' },
  { id: 'island-escape', name: '離島出走兩天遊', emoji: '🏝️', category: 'routes', lat: 22.2100, lng: 114.0280, section: 'routes', link: 'explore.html#routes' },
  { id: 'ozone-bar', name: 'Ozone酒吧', emoji: '🍸', category: 'adult', lat: 22.3000, lng: 114.1600, section: 'adult', link: 'explore.html#adult' },
  { id: 'red-sugar', name: 'Red Sugar 紅糖', emoji: '🍹', category: 'adult', lat: 22.3040, lng: 114.1910, section: 'adult', link: 'explore.html#adult' },
  { id: 'peninsula-tea', name: '半島酒店大堂茶座', emoji: '☕', category: 'adult', lat: 22.2950, lng: 114.1710, section: 'adult', link: 'explore.html#adult' },

  // ====== Food page additions ======
  { id: 'lee-keung-kei', name: '利強記北角雞蛋仔', emoji: '🥚', category: 'food', lat: 22.2910, lng: 114.2000, section: 'food', link: 'food.html#street-food' },
  { id: 'wah-sou', name: '華嫂冰室', emoji: '🍞', category: 'food', lat: 22.3140, lng: 114.2250, section: 'food', link: 'food.html#cha-chaan-teng' },
  { id: 'kai-kai-dessert', name: '佳佳甜品', emoji: '🍮', category: 'food', lat: 22.3070, lng: 114.1700, section: 'food', link: 'food.html#dessert' },
  { id: 'tim-ho-wan-ssp', name: '添好運 (深水埗)', emoji: '🥟', category: 'food', lat: 22.3290, lng: 114.1610, section: 'food', link: 'food.html#dim-sum' },
  { id: 'chai-hing-siu-mei', name: '再興燒臘', emoji: '🍗', category: 'food', lat: 22.2770, lng: 114.1730, section: 'food', link: 'food.html#roast' },
  { id: 'chan-kan-kee', name: '陳勤記 · 米芝蓮必比登潮州菜', emoji: '🥢', category: 'food', lat: 22.3070, lng: 114.1700, section: 'food', link: 'food.html#chiu-chow' },
  { id: 'man-kei-noodles', name: '文記車仔麵 · 深水埗車仔麵之王', emoji: '🍜', category: 'food', lat: 22.3310, lng: 114.1620, section: 'food', link: 'food.html#cart-noodles' },

  // ====== Snorkeling spots ======
  { id: 'hoi-ha-wan', name: '海下灣海岸公園', emoji: '🪸', category: 'snorkeling', lat: 22.4730, lng: 114.3320, section: 'snorkeling', link: 'snorkeling.html#beginner' },
  { id: 'half-moon-bay', name: '廈門灣 (半月灣)', emoji: '🏖️', category: 'snorkeling', lat: 22.3680, lng: 114.2910, section: 'snorkeling', link: 'snorkeling.html#beginner' },
  { id: 'triple-bay', name: '三星灣', emoji: '⭐', category: 'snorkeling', lat: 22.3620, lng: 114.2730, section: 'snorkeling', link: 'snorkeling.html#beginner' },
  { id: 'yim-tin-tsai', name: '鹽田梓', emoji: '🧂', category: 'snorkeling', lat: 22.3700, lng: 114.3050, section: 'snorkeling', link: 'snorkeling.html#intermediate' },
  { id: 'tung-sam-kei', name: '東心淇', emoji: '🏝️', category: 'snorkeling', lat: 22.4470, lng: 114.3510, section: 'snorkeling', link: 'snorkeling.html#intermediate' },
  { id: 'ninepin', name: '果洲群島', emoji: '🪨', category: 'snorkeling', lat: 22.2170, lng: 114.3470, section: 'snorkeling', link: 'snorkeling.html#expert' },
  { id: 'ng-mei-chau', name: '娥眉洲', emoji: '🌊', category: 'snorkeling', lat: 22.5100, lng: 114.2900, section: 'snorkeling', link: 'snorkeling.html#expert' },
  { id: 'ung-kong', name: '甕缸群島', emoji: '🏔️', category: 'snorkeling', lat: 22.2400, lng: 114.3600, section: 'snorkeling', link: 'snorkeling.html#expert' },

  // ====== Hiking trails ======
  { id: 'hiking-dragons-back', name: '龍脊 (Dragon\'s Back)', emoji: '🐉', category: 'hiking', lat: 22.2300, lng: 114.2400, section: 'hiking', link: 'hiking-dragons-back.html' },
  { id: 'hiking-peak-circle', name: '太平山頂環山步道', emoji: '🏔️', category: 'hiking', lat: 22.2760, lng: 114.1450, section: 'hiking', link: 'hiking-peak-circle.html' },
  { id: 'hiking-por-lo-shan', name: '菠蘿山良田坳峽谷', emoji: '🏜️', category: 'hiking', lat: 22.4000, lng: 113.9700, section: 'hiking', link: 'hiking-por-lo-shan.html' },
  { id: 'hiking-lamma', name: '南丫島家樂徑', emoji: '🏝️', category: 'hiking', lat: 22.2000, lng: 114.1000, section: 'hiking', link: 'hiking-lamma-island.html' },
  { id: 'hiking-lion-rock', name: '獅子山', emoji: '🦁', category: 'hiking', lat: 22.3500, lng: 114.1900, section: 'hiking', link: 'hiking-lion-rock.html' },
  { id: 'hiking-tai-mo-shan', name: '大帽山', emoji: '⛰️', category: 'hiking', lat: 22.4100, lng: 114.1200, section: 'hiking', link: 'hiking-tai-mo-shan.html' },
  { id: 'hiking-high-junk', name: '釣魚翁', emoji: '🎣', category: 'hiking', lat: 22.3000, lng: 114.2900, section: 'hiking', link: 'hiking-high-junk-peak.html' },
  { id: 'hiking-thousand-islands', name: '千島湖', emoji: '🏞️', category: 'hiking', lat: 22.4400, lng: 114.0100, section: 'hiking', link: 'hiking-thousand-islands.html' },
  { id: 'hiking-maclehose-s2', name: '麥理浩徑第二段', emoji: '🥾', category: 'hiking', lat: 22.4000, lng: 114.3200, section: 'hiking', link: 'hiking-maclehose-s2.html' },
  { id: 'hiking-sunset-peak', name: '大東山 (日落大草坪)', emoji: '🌅', category: 'hiking', lat: 22.2700, lng: 113.9600, section: 'hiking', link: 'hiking-sunset-peak.html' },
  { id: 'hiking-tung-o', name: '東澳古道', emoji: '🏘️', category: 'hiking', lat: 22.2800, lng: 113.9300, section: 'hiking', link: 'hiking-tung-o-trail.html' },
  { id: 'hiking-cape-daguilar', name: '鶴咀海岸保護區', emoji: '🦀', category: 'hiking', lat: 22.2100, lng: 114.2600, section: 'hiking', link: 'hiking-cape-daguilar.html' },
  { id: 'hiking-shing-mun', name: '城門水塘', emoji: '🌳', category: 'hiking', lat: 22.3800, lng: 114.1600, section: 'hiking', link: 'hiking-shing-mun.html' },
  { id: 'hiking-yuen-tsuen', name: '元荃古道', emoji: '🏯', category: 'hiking', lat: 22.3900, lng: 114.0800, section: 'hiking', link: 'hiking-yuen-tsuen.html' },

  { id: 'snork-sharp-island', name: '橋咀洲', emoji: '🌴', category: 'snorkeling', lat: 22.363, lng: 114.296, section: 'snorkeling', link: 'snorkeling-sharp-island.html' },
  { id: 'snork-hoi-ha-wan', name: '海下灣', emoji: '🪸', category: 'snorkeling', lat: 22.473, lng: 114.332, section: 'snorkeling', link: 'snorkeling-hoi-ha-wan.html' },
  { id: 'snork-half-moon-bay', name: '廈門灣', emoji: '🏖️', category: 'snorkeling', lat: 22.368, lng: 114.291, section: 'snorkeling', link: 'snorkeling-half-moon-bay.html' },
  { id: 'snork-triple-bay', name: '三星灣', emoji: '⭐', category: 'snorkeling', lat: 22.362, lng: 114.273, section: 'snorkeling', link: 'snorkeling-triple-bay.html' },
  { id: 'snork-green-egg', name: '綠蛋島', emoji: '🥚', category: 'snorkeling', lat: 22.283, lng: 114.317, section: 'snorkeling', link: 'snorkeling-green-egg.html' },
  { id: 'snork-yim-tin-tsai', name: '鹽田梓', emoji: '🧂', category: 'snorkeling', lat: 22.37, lng: 114.305, section: 'snorkeling', link: 'snorkeling-yim-tin-tsai.html' },
  { id: 'snork-grass-island', name: '塔門', emoji: '🌿', category: 'snorkeling', lat: 22.47, lng: 114.36, section: 'snorkeling', link: 'snorkeling-grass-island.html' },
  { id: 'snork-tung-sam-kei', name: '東心淇', emoji: '🏝️', category: 'snorkeling', lat: 22.447, lng: 114.351, section: 'snorkeling', link: 'snorkeling-tung-sam-kei.html' },
  { id: 'snork-tung-ping-chau', name: '東平洲', emoji: '🗿', category: 'snorkeling', lat: 22.535, lng: 114.43, section: 'snorkeling', link: 'snorkeling-tung-ping-chau.html' },
  { id: 'snork-ninepin', name: '果洲群島', emoji: '🪨', category: 'snorkeling', lat: 22.217, lng: 114.347, section: 'snorkeling', link: 'snorkeling-ninepin.html' },
  { id: 'snork-ng-mei-chau', name: '娥眉洲', emoji: '🌊', category: 'snorkeling', lat: 22.51, lng: 114.29, section: 'snorkeling', link: 'snorkeling-ng-mei-chau.html' },
  { id: 'snork-ung-kong', name: '甕缸群島', emoji: '🏔️', category: 'snorkeling', lat: 22.24, lng: 114.36, section: 'snorkeling', link: 'snorkeling-ung-kong.html' },
  { id: 'swimming-victoria-park', name: '維多利亞公園游泳池', emoji: '🏊', category: 'swimming', lat: 22.282, lng: 114.19, section: 'swimming', link: 'swimming-victoria-park.html' },
  { id: 'swimming-kennedy-town', name: '堅尼地城游泳池', emoji: '🌊', category: 'swimming', lat: 22.281, lng: 114.127, section: 'swimming', link: 'swimming-kennedy-town.html' },
  { id: 'swimming-morrison-hill', name: '摩理臣山游泳池', emoji: '🏅', category: 'swimming', lat: 22.278, lng: 114.178, section: 'swimming', link: 'swimming-morrison-hill.html' },
  { id: 'swimming-kowloon-park', name: '九龍公園游泳池', emoji: '🌴', category: 'swimming', lat: 22.301, lng: 114.17, section: 'swimming', link: 'swimming-kowloon-park.html' },
  { id: 'swimming-kwun-tong', name: '觀塘游泳池', emoji: '🏗️', category: 'swimming', lat: 22.312, lng: 114.226, section: 'swimming', link: 'swimming-kwun-tong.html' },
  { id: 'swimming-lai-chi-kok', name: '荔枝角公園游泳池', emoji: '🌳', category: 'swimming', lat: 22.338, lng: 114.136, section: 'swimming', link: 'swimming-lai-chi-kok.html' },
  { id: 'swimming-tuen-mun-northwest', name: '屯門西北游泳池', emoji: '🏊', category: 'swimming', lat: 22.404, lng: 113.971, section: 'swimming', link: 'swimming-tuen-mun-northwest.html' },
  { id: 'swimming-sha-tin', name: '沙田賽馬會游泳池', emoji: '🏇', category: 'swimming', lat: 22.385, lng: 114.188, section: 'swimming', link: 'swimming-sha-tin.html' },
  { id: 'swimming-tseung-kwan-o', name: '將軍澳游泳池', emoji: '🌅', category: 'swimming', lat: 22.307, lng: 114.258, section: 'swimming', link: 'swimming-tseung-kwan-o.html' },
  { id: 'swimming-golden-beach', name: '黃金泳灘 / 加多利灣', emoji: '🏖️', category: 'swimming', lat: 22.371, lng: 113.995, section: 'swimming', link: 'swimming-golden-beach.html' },
  { id: 'swimming-repulse-bay', name: '淺水灣', emoji: '🌊', category: 'swimming', lat: 22.236, lng: 114.196, section: 'swimming', link: 'swimming-repulse-bay.html' },
  { id: 'swimming-hotel-day-pass', name: '酒店泳池 Day Pass', emoji: '🏨', category: 'swimming', lat: 22.298, lng: 114.169, section: 'swimming', link: 'swimming-hotel-day-pass.html' },
  { id: 'swimming-hksi', name: '香港體育學院泳池', emoji: '🏅', category: 'swimming', lat: 22.395, lng: 114.202, section: 'swimming', link: 'swimming-hksi.html' },

  // ====== Electronics ======
  { id: 'electronics-golden-arcade', name: '黃金電腦商場', emoji: '🖥️', category: 'electronics', lat: 22.330, lng: 114.160, section: 'electronics', link: 'electronics-golden-arcade.html' },
  { id: 'electronics-golden-centre', name: '高登電腦中心', emoji: '💾', category: 'electronics', lat: 22.329, lng: 114.161, section: 'electronics', link: 'electronics-golden-centre.html' },
  { id: 'electronics-new-golden', name: '新高登電腦廣場', emoji: '🔧', category: 'electronics', lat: 22.330, lng: 114.159, section: 'electronics', link: 'electronics-new-golden.html' },
  { id: 'electronics-wan-chai', name: '灣仔電腦城', emoji: '🏢', category: 'electronics', lat: 22.279, lng: 114.173, section: 'electronics', link: 'electronics-wan-chai.html' },
  { id: 'electronics-oriental-188', name: '東方188商場', emoji: '🎮', category: 'electronics', lat: 22.278, lng: 114.172, section: 'electronics', link: 'electronics-oriental-188.html' },
  { id: 'electronics-sino-centre', name: '信和中心', emoji: '🎯', category: 'electronics', lat: 22.317, lng: 114.170, section: 'electronics', link: 'electronics-sino-centre.html' },
  { id: 'electronics-golden-gaming', name: '黃金/高登遊戲', emoji: '🕹️', category: 'electronics', lat: 22.329, lng: 114.161, section: 'electronics', link: 'electronics-golden-gaming.html' },
  { id: 'electronics-sim-city', name: '星際城市', emoji: '📸', category: 'electronics', lat: 22.319, lng: 114.170, section: 'electronics', link: 'electronics-sim-city.html' },
  { id: 'electronics-wing-shing-mong-shing', name: '永成萬成', emoji: '🏪', category: 'electronics', lat: 22.319, lng: 114.171, section: 'electronics', link: 'electronics-wing-shing-mong-shing.html' },
  { id: 'electronics-sin-tat', name: '先達廣場', emoji: '📱', category: 'electronics', lat: 22.318, lng: 114.169, section: 'electronics', link: 'electronics-sin-tat.html' },
  { id: 'electronics-ap-liu-street', name: '鴨寮街', emoji: '🔌', category: 'electronics', lat: 22.328, lng: 114.162, section: 'electronics', link: 'electronics-ap-liu-street.html' },


  // ====== Restaurant detail pages (generated) ======
  { id: 'food-red-tea-house', name: '紅茶冰室', emoji: '🥇', category: 'food', lat: 22.296, lng: 114.171, section: 'food', link: 'food-red-tea-house.html' },
  { id: 'food-wah-sou', name: '華嫂冰室', emoji: '🍞', category: 'food', lat: 22.314, lng: 114.225, section: 'food', link: 'food-wah-sou.html' },
  { id: 'food-australia-dairy', name: '澳洲牛奶公司', emoji: '🥪', category: 'food', lat: 22.305, lng: 114.169, section: 'food', link: 'food-australia-dairy.html' },
  { id: 'food-wong-gee', name: '旺記冰室', emoji: '🧈', category: 'food', lat: 22.278, lng: 114.173, section: 'food', link: 'food-wong-gee.html' },
  { id: 'food-lee-keung-kei', name: '利強記北角雞蛋仔', emoji: '🥚', category: 'food', lat: 22.291, lng: 114.2, section: 'food', link: 'food-lee-keung-kei.html' },
  { id: 'food-lee-tung-fishballs', name: '利東街炸魚蛋', emoji: '🐟', category: 'food', lat: 22.276, lng: 114.171, section: 'food', link: 'food-lee-tung-fishballs.html' },
  { id: 'food-kung-so', name: '公和荳品廠', emoji: '🥟', category: 'food', lat: 22.33, lng: 114.162, section: 'food', link: 'food-kung-so.html' },
  { id: 'food-mommy-eggette', name: '媽咪雞蛋仔', emoji: '🍡', category: 'food', lat: 22.303, lng: 114.188, section: 'food', link: 'food-mommy-eggette.html' },
  { id: 'food-choi-hing', name: '再興燒臘', emoji: '🍗', category: 'food', lat: 22.277, lng: 114.173, section: 'food', link: 'food-choi-hing.html' },
  { id: 'food-yung-kee', name: '鏞記酒家', emoji: '🥩', category: 'food', lat: 22.281, lng: 114.155, section: 'food', link: 'food-yung-kee.html' },
  { id: 'food-yat-lok', name: '一樂燒鵝', emoji: '🦆', category: 'food', lat: 22.283, lng: 114.155, section: 'food', link: 'food-yat-lok.html' },
  { id: 'food-sun-kwai-heung', name: '新桂香燒臘', emoji: '🐷', category: 'food', lat: 22.264, lng: 114.237, section: 'food', link: 'food-sun-kwai-heung.html' },
  { id: 'food-tim-ho-wan-ssp', name: '添好運 (深水埗)', emoji: '🥟', category: 'food', lat: 22.329, lng: 114.161, section: 'food', link: 'food-tim-ho-wan-ssp.html' },
  { id: 'food-lin-heung', name: '蓮香樓', emoji: '🫖', category: 'food', lat: 22.286, lng: 114.151, section: 'food', link: 'food-lin-heung.html' },
  { id: 'food-luk-yu', name: '陸羽茶室', emoji: '🥢', category: 'food', lat: 22.281, lng: 114.156, section: 'food', link: 'food-luk-yu.html' },
  { id: 'food-kai-kai-dessert', name: '佳佳甜品', emoji: '🍮', category: 'food', lat: 22.307, lng: 114.17, section: 'food', link: 'food-kai-kai-dessert.html' },
  { id: 'food-chung-so', name: '聰嫂甜品', emoji: '🍨', category: 'food', lat: 22.28, lng: 114.185, section: 'food', link: 'food-chung-so.html' },
  { id: 'food-tai-leung', name: '大良八記', emoji: '🥣', category: 'food', lat: 22.318, lng: 114.17, section: 'food', link: 'food-tai-leung.html' },
  { id: 'food-chan-kan-kee', name: '陳勤記', emoji: '🥢', category: 'food', lat: 22.287, lng: 114.15, section: 'food', link: 'food-chan-kan-kee.html' },
  { id: 'food-sheung-hing', name: '尚興潮州飯店', emoji: '🦪', category: 'food', lat: 22.287, lng: 114.151, section: 'food', link: 'food-sheung-hing.html' },
  { id: 'food-man-kei', name: '文記車仔麵', emoji: '🍜', category: 'food', lat: 22.331, lng: 114.162, section: 'food', link: 'food-man-kei.html' },
  { id: 'food-wing-kei', name: '榮記車仔麵', emoji: '🍲', category: 'food', lat: 22.28, lng: 114.185, section: 'food', link: 'food-wing-kei.html' },
  { id: 'food-kwan-kee', name: '坤記煲仔小菜', emoji: '🍚', category: 'food', lat: 22.287, lng: 114.143, section: 'food', link: 'food-kwan-kee.html' },
  { id: 'food-hing-kee', name: '興記煲仔飯', emoji: '🍚', category: 'food', lat: 22.305, lng: 114.169, section: 'food', link: 'food-hing-kee.html' },
  { id: 'food-bridge-bottom', name: '橋底辣蟹', emoji: '🦐', category: 'food', lat: 22.276, lng: 114.174, section: 'food', link: 'food-bridge-bottom.html' },
  { id: 'food-chuen-kee', name: '全記海鮮', emoji: '🦞', category: 'food', lat: 22.381, lng: 114.274, section: 'food', link: 'food-chuen-kee.html' },
  { id: 'food-kau-kee', name: '九記牛腩', emoji: '🍝', category: 'food', lat: 22.284, lng: 114.153, section: 'food', link: 'food-kau-kee.html' },
  { id: 'food-18-seats', name: '十八座狗仔粉', emoji: '🍜', category: 'food', lat: 22.329, lng: 114.161, section: 'food', link: 'food-18-seats.html' },
  { id: 'food-islamic-beef', name: '清真牛肉館', emoji: '🥟', category: 'food', lat: 22.327, lng: 114.188, section: 'food', link: 'food-islamic-beef.html' },
]
  { id: 'food-lan-fong-yuen', name: '蘭芳園', emoji: '🫖', category: 'food', lat: 22.281, lng: 114.155, section: 'food', link: 'food-lan-fong-yuen.html' },
  { id: 'food-bing-kee', name: '炳記茶檔', emoji: '🏆', category: 'food', lat: 22.28, lng: 114.19, section: 'food', link: 'food-bing-kee.html' },
  { id: 'food-hop-yick-tai', name: '合益泰小食', emoji: '🥟', category: 'food', lat: 22.33, lng: 114.162, section: 'food', link: 'food-hop-yick-tai.html' },
  { id: 'food-tung-tat', name: '通達食店', emoji: '🥣', category: 'food', lat: 22.312, lng: 114.17, section: 'food', link: 'food-tung-tat.html' },
  { id: 'food-kam-shao-wan', name: '甘牌燒鵝', emoji: '🥇', category: 'food', lat: 22.278, lng: 114.174, section: 'food', link: 'food-kam-shao-wan.html' },
  { id: 'food-sun-hing', name: '新興食家', emoji: '🌙', category: 'food', lat: 22.282, lng: 114.129, section: 'food', link: 'food-sun-hing.html' },
  { id: 'food-bakehouse', name: 'Bakehouse', emoji: '🥐', category: 'food', lat: 22.281, lng: 114.155, section: 'food', link: 'food-bakehouse.html' },
  { id: 'food-yuk-yip', name: '玉葉甜品', emoji: '🌿', category: 'food', lat: 22.283, lng: 114.153, section: 'food', link: 'food-yuk-yip.html' },
  { id: 'food-hee-kee', name: '喜記避風塘炒辣蟹', emoji: '🦀', category: 'food', lat: 22.28, lng: 114.182, section: 'food', link: 'food-hee-kee.html' },
  { id: 'food-little-bao', name: 'Little Bao', emoji: '🍔', category: 'food', lat: 22.284, lng: 114.152, section: 'food', link: 'food-little-bao.html' },
];
